name: Hourly Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update_top_games:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6

      - name: Navigate to backend dir
        run: cd server

      - name: Install dependancies
        run: npm --prefix ./server i

      - name: Run game update scripts
        env:
          MONGO_CI_USERNAME: ${{ secrets.MONGO_CI_USERNAME }}
          MONGO_CI_PASSWORD: ${{ secrets.MONGO_CI_PASSWORD }}
        run: npm --prefix ./server run update_top_games
